dbt_dwh_transform:
  target: dev
  outputs:
    silver:
      dataset: akmal_ecommerce_silver_capstone3
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: ../keys/jcdeah-006-b18fd9371986.json
      location: asia-southeast2
      method: service-account
      priority: interactive
      project: jcdeah-006
      threads: 6
      type: bigquery
    gold:
      dataset: akmal_ecommerce_gold_capstone3
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: ../keys/jcdeah-006-b18fd9371986.json
      location: asia-southeast2
      method: service-account
      priority: interactive
      project: jcdeah-006
      threads: 6
      type: bigquery
  
