dbt_dwh_transform:
  outputs:
    dev:
      dataset: akmal_ecommerce_bronze_capstone3
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: keys/jcdeah-006-b18fd9371986.json
      location: US
      method: service-account
      priority: interactive
      project: jcdeah-006
      threads: 6
      type: bigquery
  target: dev
